/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package avro;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;
;


@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class canInfo extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5359778347980227969L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"canInfo\",\"namespace\":\"avro\",\"fields\":[{\"name\":\"canId\",\"type\":\"string\"},{\"name\":\"canTime\",\"type\":[\"long\",\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<canInfo> ENCODER =
      new BinaryMessageEncoder<canInfo>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<canInfo> DECODER =
      new BinaryMessageDecoder<canInfo>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<canInfo> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<canInfo> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<canInfo>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this canInfo to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a canInfo from a ByteBuffer. */
  public static canInfo fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence canId;
  @Deprecated public java.lang.Long canTime;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public canInfo() {}

  /**
   * All-args constructor.
   * @param canId The new value for canId
   * @param canTime The new value for canTime
   */
  public canInfo(java.lang.CharSequence canId, java.lang.Long canTime) {
    this.canId = canId;
    this.canTime = canTime;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return canId;
    case 1: return canTime;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: canId = (java.lang.CharSequence)value$; break;
    case 1: canTime = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'canId' field.
   * @return The value of the 'canId' field.
   */
  public java.lang.CharSequence getCanId() {
    return canId;
  }

  /**
   * Sets the value of the 'canId' field.
   * @param value the value to set.
   */
  public void setCanId(java.lang.CharSequence value) {
    this.canId = value;
  }

  /**
   * Gets the value of the 'canTime' field.
   * @return The value of the 'canTime' field.
   */
  public java.lang.Long getCanTime() {
    return canTime;
  }

  /**
   * Sets the value of the 'canTime' field.
   * @param value the value to set.
   */
  public void setCanTime(java.lang.Long value) {
    this.canTime = value;
  }

  /**
   * Creates a new canInfo RecordBuilder.
   * @return A new canInfo RecordBuilder
   */
  public static avro.canInfo.Builder newBuilder() {
    return new avro.canInfo.Builder();
  }

  /**
   * Creates a new canInfo RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new canInfo RecordBuilder
   */
  public static avro.canInfo.Builder newBuilder(avro.canInfo.Builder other) {
    return new avro.canInfo.Builder(other);
  }

  /**
   * Creates a new canInfo RecordBuilder by copying an existing canInfo instance.
   * @param other The existing instance to copy.
   * @return A new canInfo RecordBuilder
   */
  public static avro.canInfo.Builder newBuilder(avro.canInfo other) {
    return new avro.canInfo.Builder(other);
  }

  /**
   * RecordBuilder for canInfo instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<canInfo>
    implements org.apache.avro.data.RecordBuilder<canInfo> {

    private java.lang.CharSequence canId;
    private java.lang.Long canTime;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(avro.canInfo.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.canId)) {
        this.canId = data().deepCopy(fields()[0].schema(), other.canId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.canTime)) {
        this.canTime = data().deepCopy(fields()[1].schema(), other.canTime);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing canInfo instance
     * @param other The existing instance to copy.
     */
    private Builder(avro.canInfo other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.canId)) {
        this.canId = data().deepCopy(fields()[0].schema(), other.canId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.canTime)) {
        this.canTime = data().deepCopy(fields()[1].schema(), other.canTime);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'canId' field.
      * @return The value.
      */
    public java.lang.CharSequence getCanId() {
      return canId;
    }

    /**
      * Sets the value of the 'canId' field.
      * @param value The value of 'canId'.
      * @return This builder.
      */
    public avro.canInfo.Builder setCanId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.canId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'canId' field has been set.
      * @return True if the 'canId' field has been set, false otherwise.
      */
    public boolean hasCanId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'canId' field.
      * @return This builder.
      */
    public avro.canInfo.Builder clearCanId() {
      canId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'canTime' field.
      * @return The value.
      */
    public java.lang.Long getCanTime() {
      return canTime;
    }

    /**
      * Sets the value of the 'canTime' field.
      * @param value The value of 'canTime'.
      * @return This builder.
      */
    public avro.canInfo.Builder setCanTime(java.lang.Long value) {
      validate(fields()[1], value);
      this.canTime = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'canTime' field has been set.
      * @return True if the 'canTime' field has been set, false otherwise.
      */
    public boolean hasCanTime() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'canTime' field.
      * @return This builder.
      */
    public avro.canInfo.Builder clearCanTime() {
      canTime = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public canInfo build() {
      try {
        canInfo record = new canInfo();
        record.canId = fieldSetFlags()[0] ? this.canId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.canTime = fieldSetFlags()[1] ? this.canTime : (java.lang.Long) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<canInfo>
    WRITER$ = (org.apache.avro.io.DatumWriter<canInfo>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<canInfo>
    READER$ = (org.apache.avro.io.DatumReader<canInfo>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
